version: "3.8"

services:

  redis:
    image: redis:7
    container_name: feedapp-redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: feedapp-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    restart: always

  # App database
  postgres-app:
    image: postgres:16
    container_name: feedapp-postgres-app-db
    environment:
      - POSTGRES_DB=feedapp
      - POSTGRES_USER=feedapp
      - POSTGRES_PASSWORD=feedapp
    volumes:
      - ./data/postgres-app:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U feedapp -d feedapp" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  # Keycloak database
  postgres-keycloak:
    image: postgres:16
    container_name: feedapp-postgres-keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - ./data/postgres-keycloak:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: feedapp-keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro
      - ./keycloak/themes:/opt/keycloak/themes:ro
    ports:
      - "8081:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    restart: always

  # todo: feedapp container
