version: "3.9"

services:
  feedapp-redis:
    image: redis:7
    container_name: feedapp-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - feedapp-net

  feedapp-rabbitmq:
    image: rabbitmq:3-management
    container_name: feedapp-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always
    networks:
      - feedapp-net

  # App database
  postgres-app:
    image: postgres:16
    container_name: feedapp-postgres-app-db
    environment:
      - POSTGRES_DB=feedapp
      - POSTGRES_USER=feedapp
      - POSTGRES_PASSWORD=feedapp
    volumes:
      - postgres-app-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U feedapp -d feedapp" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    networks:
      - feedapp-net

  # Keycloak database
  postgres-keycloak:
    image: postgres:16
    container_name: feedapp-postgres-keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    networks:
      - feedapp-net

  feedapp-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: feedapp-keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro
      - ./keycloak/themes:/opt/keycloak/themes:ro
    ports:
      - "8081:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    restart: always
    networks:
      - feedapp-net

  # The app
  feedapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-matejvvo}/feedapp:${TAG:-latest}
    container_name: feedapp
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - APP_DB_HOST=postgres-app
      - APP_DB_PORT=5432
      - KEYCLOAK_HOST=feedapp-keycloak
      - KEYCLOAK_PORT=8080
      - REDIS_HOST=feedapp-redis
      - REDIS_PORT=6379
      - RABBIT_MQ_HOST=feedapp-rabbitmq
      - RABBIT_MQ_PORT=5672
    depends_on:
      postgres-app:
        condition: service_healthy
      postgres-keycloak:
        condition: service_healthy
      feedapp-keycloak:
        condition: service_started
      feedapp-redis:
        condition: service_healthy
      feedapp-rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - feedapp-net

networks:
  feedapp-net:
    driver: bridge

volumes:
  postgres-app-data:
  postgres-keycloak-data:
  redis-data:
  rabbitmq-data:
