name: build-and-deploy

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 24
#        uses: actions/setup-java@v4
#        with:
#          java-version: '24'
#          distribution: 'temurin'
#
#      - name: Install frontend dependencies
#        working-directory: frontend
#        run: npx npm ci
#
#      - name: Set up Gradle cache
#        uses: gradle/actions/setup-gradle@v4
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Run all JUnit tests
#        run: ./gradlew clean test --info --stacktrace

  docker:
#    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ vars.DOCKERHUB_USER }}
      TAG:  ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          export TAG=${TAG}
          export DOCKER_USER=${DOCKER_USER}
          docker compose build feedapp
          docker compose push feedapp
