name: test

on:
  workflow_dispatch:
  push:
    branches: [ main, matej ]
    paths:
      - 'backend/src/**'
      - 'frontend/src/**'
      - '**/*.java'
      - '**/*.kts'
      - '**/*.properties'
jobs:
  junittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npx npm ci

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run all JUnit tests
        run: ./gradlew clean test --info --stacktrace
